lib/my_farm_web/router.ex
defmodule MyFarmWeb.Router do
  use MyFarmWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {MyFarmWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MyFarmWeb do
    pipe_through :browser

    get "/", PageController, :index

    live "/farms", FarmLive.Index, :index
    live "/farms/new", FarmLive.Index, :new
    live "/farms/:id/edit", FarmLive.Index, :edit

    live "/farms/:id", FarmLive.Show, :show
    live "/farms/:id/show/edit", FarmLive.Show, :edit
  end

  scope "/api" do
    pipe_through :api

    forward "/graphiql", Absinthe.Plug.GraphiQL,
      schema: MyFarmWeb.Schema,
      interface: :simple,
      context: %{pubsub: MyFarmWeb.Endpoint}

    forward "/", Absinthe.Plug, schema: MyFarmWeb.Schema
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: MyFarmWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/my_farm_web/live/farm_live/form_component.ex
defmodule MyFarmWeb.FarmLive.FormComponent do
  use MyFarmWeb, :live_component

  alias MyFarm.Farms

  @impl true
  def update(%{farm: farm} = assigns, socket) do
    changeset = Farms.change_farm(farm)

    {:ok,
     socket
     |> assign(assigns)
     |> assign(:changeset, changeset)}
  end

  @impl true
  def handle_event("validate", %{"farm" => farm_params}, socket) do
    changeset =
      socket.assigns.farm
      |> Farms.change_farm(farm_params)
      |> Map.put(:action, :validate)

    {:noreply, assign(socket, :changeset, changeset)}
  end

  def handle_event("save", %{"farm" => farm_params}, socket) do
    save_farm(socket, socket.assigns.action, farm_params)
  end

  defp save_farm(socket, :edit, farm_params) do
    case Farms.update_farm(socket.assigns.farm, farm_params) do
      {:ok, _farm} ->
        {:noreply,
         socket
         |> put_flash(:info, "Farm updated successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, :changeset, changeset)}
    end
  end

  defp save_farm(socket, :new, farm_params) do
    case Farms.create_farm(farm_params) do
      {:ok, _farm} ->
        {:noreply,
         socket
         |> put_flash(:info, "Farm created successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end
end

lib/my_farm_web/live/farm_live/index.ex
defmodule MyFarmWeb.FarmLive.Index do
  use MyFarmWeb, :live_view

  alias MyFarm.Farms
  alias MyFarm.Farms.Farm

  @impl true
  def mount(_params, _session, socket) do
    {:ok, assign(socket, :farms, list_farms())}
  end

  @impl true
  def handle_params(params, _url, socket) do
    {:noreply, apply_action(socket, socket.assigns.live_action, params)}
  end

  defp apply_action(socket, :edit, %{"id" => id}) do
    socket
    |> assign(:page_title, "Edit Farm")
    |> assign(:farm, Farms.get_farm!(id))
  end

  defp apply_action(socket, :new, _params) do
    socket
    |> assign(:page_title, "New Farm")
    |> assign(:farm, %Farm{})
  end

  defp apply_action(socket, :index, _params) do
    socket
    |> assign(:page_title, "Listing Farms")
    |> assign(:farm, nil)
  end

  @impl true
  def handle_event("delete", %{"id" => id}, socket) do
    farm = Farms.get_farm!(id)
    {:ok, _} = Farms.delete_farm(farm)

    {:noreply, assign(socket, :farms, list_farms())}
  end

  defp list_farms do
    Farms.list_farms()
  end
end

lib/my_farm_web/live/farm_live/show.ex
defmodule MyFarmWeb.FarmLive.Show do
  use MyFarmWeb, :live_view

  alias MyFarm.Farms

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(%{"id" => id}, _, socket) do
    {:noreply,
     socket
     |> assign(:page_title, page_title(socket.assigns.live_action))
     |> assign(:farm, Farms.get_farm!(id))}
  end

  defp page_title(:show), do: "Show Farm"
  defp page_title(:edit), do: "Edit Farm"
end

lib/my_farm_web/live/live_helpers.ex
defmodule MyFarmWeb.LiveHelpers do
  import Phoenix.LiveView
  import Phoenix.LiveView.Helpers

  alias Phoenix.LiveView.JS

  @doc """
  Renders a live component inside a modal.

  The rendered modal receives a `:return_to` option to properly update
  the URL when the modal is closed.

  ## Examples

      <.modal return_to={Routes.farm_index_path(@socket, :index)}>
        <.live_component
          module={MyFarmWeb.FarmLive.FormComponent}
          id={@farm.id || :new}
          title={@page_title}
          action={@live_action}
          return_to={Routes.farm_index_path(@socket, :index)}
          farm: @farm
        />
      </.modal>
  """
  def modal(assigns) do
    assigns = assign_new(assigns, :return_to, fn -> nil end)

    ~H"""
    <div id="modal" class="phx-modal fade-in" phx-remove={hide_modal()}>
      <div
        id="modal-content"
        class="phx-modal-content fade-in-scale"
        phx-click-away={JS.dispatch("click", to: "#close")}
        phx-window-keydown={JS.dispatch("click", to: "#close")}
        phx-key="escape"
      >
        <%= if @return_to do %>
          <%= live_patch "✖",
            to: @return_to,
            id: "close",
            class: "phx-modal-close",
            phx_click: hide_modal()
          %>
        <% else %>
          <a id="close" href="#" class="phx-modal-close" phx-click={hide_modal()}>✖</a>
        <% end %>

        <%= render_slot(@inner_block) %>
      </div>
    </div>
    """
  end

  defp hide_modal(js \\ %JS{}) do
    js
    |> JS.hide(to: "#modal", transition: "fade-out")
    |> JS.hide(to: "#modal-content", transition: "fade-out-scale")
  end
end

lib/my_farm_web/live/farm_live/form_component.html.heex
<div>
  <h2><%= @title %></h2>

  <.form
    let={f}
    for={@changeset}
    id="farm-form"
    phx-target={@myself}
    phx-change="validate"
    phx-submit="save">
  
    <%= label f, :name %>
    <%= text_input f, :name %>
    <%= error_tag f, :name %>
  
    <%= label f, :owner %>
    <%= text_input f, :owner %>
    <%= error_tag f, :owner %>
  
    <div>
      <%= submit "Save", phx_disable_with: "Saving..." %>
    </div>
  </.form>
</div>

lib/my_farm_web/live/farm_live/index.html.heex
<h1>Listing Farms</h1>

<%= if @live_action in [:new, :edit] do %>
  <.modal return_to={Routes.farm_index_path(@socket, :index)}>
    <.live_component
      module={MyFarmWeb.FarmLive.FormComponent}
      id={@farm.id || :new}
      title={@page_title}
      action={@live_action}
      farm={@farm}
      return_to={Routes.farm_index_path(@socket, :index)}
    />
  </.modal>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Owner</th>

      <th></th>
    </tr>
  </thead>
  <tbody id="farms">
    <%= for farm <- @farms do %>
      <tr id={"farm-#{farm.id}"}>
        <td><%= farm.name %></td>
        <td><%= farm.owner %></td>

        <td>
          <span><%= live_redirect "Show", to: Routes.farm_show_path(@socket, :show, farm) %></span>
          <span><%= live_patch "Edit", to: Routes.farm_index_path(@socket, :edit, farm) %></span>
          <span><%= link "Delete", to: "#", phx_click: "delete", phx_value_id: farm.id, data: [confirm: "Are you sure?"] %></span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<span><%= live_patch "New Farm", to: Routes.farm_index_path(@socket, :new) %></span>

lib/my_farm_web/live/farm_live/show.html.heex
<h1>Show Farm</h1>

<%= if @live_action in [:edit] do %>
  <.modal return_to={Routes.farm_show_path(@socket, :show, @farm)}>
    <.live_component
      module={MyFarmWeb.FarmLive.FormComponent}
      id={@farm.id}
      title={@page_title}
      action={@live_action}
      farm={@farm}
      return_to={Routes.farm_show_path(@socket, :show, @farm)}
    />
  </.modal>
<% end %>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @farm.name %>
  </li>

  <li>
    <strong>Owner:</strong>
    <%= @farm.owner %>
  </li>

</ul>

<span><%= live_patch "Edit", to: Routes.farm_show_path(@socket, :edit, @farm), class: "button" %></span> |
<span><%= live_redirect "Back", to: Routes.farm_index_path(@socket, :index) %></span>